# Generated by Django 4.1.4 on 2022-12-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("birthdate", models.IntegerField(blank=True)),
                ("address", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=100)),
                ("image", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
