# Generated by Django 4.1.4 on 2022-12-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_basicinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinfo",
            name="birthdate",
            field=models.DateField(blank=True),
        ),
    ]
