# Generated by Django 4.1.4 on 2023-01-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_school_comment_alter_school_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="end_date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="school",
            name="start_date",
            field=models.CharField(max_length=100),
        ),
    ]
