# Generated by Django 4.1.4 on 2023-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_school_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
