# Generated by Django 4.1.4 on 2023-02-04 14:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_programingproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="programingproject",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_to
            ),
        ),
    ]
