# Generated by Django 4.1.4 on 2023-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_programingproject_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programingproject",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
    ]
