# Generated by Django 4.1.4 on 2023-02-04 15:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_programingproject_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programingproject",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
