# Generated by Django 4.1.4 on 2023-02-05 16:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_programingproject_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinfo",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
