# Generated by Django 4.1.4 on 2023-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_basicinfo_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="programingproject",
            name="git_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
