# Generated by Django 4.1.4 on 2023-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_programingproject_git_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programingproject",
            name="git_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
